site_name: Pattern Analyzer Documentation
site_description: "Documentation for Pattern Analyzer, a binary pattern analysis framework."
site_author: EdgeTypE
repo_url: https://github.com/EdgeTypE/pattern-analyzer
site_url: https://EdgeTypE.github.io/pattern-analyzer
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Plugin Developer Guide: plugin-developer-guide.md
  - API Reference: api-reference.md
  - Test Reference: test-reference.md
  - Configs:
      - Example YAML: configs/example.yml
      - Example JSON: configs/example.json
theme:
  name: material
plugins:
  - search